const DIRECTION_UP = 'up'
const DIRECTION_DOWN = 'down'
const DIRECTION_RIGHT = 'right'
const DIRECTION_LEFT = 'left'

const DIRECTION_UP_LEFT = 'up_left'
const DIRECTION_UP_RIGHT = 'up_right'
const DIRECTION_DOWN_LEFT = 'down_left'
const DIRECTION_DOWN_RIGHT = 'down_right'

const DIRECTIONS = [
  DIRECTION_DOWN,
  DIRECTION_DOWN_RIGHT,
  DIRECTION_RIGHT,
  DIRECTION_UP_RIGHT,
  DIRECTION_UP,
  DIRECTION_UP_LEFT,
  DIRECTION_LEFT,
  DIRECTION_DOWN_LEFT
]
